serverConfig:
  connectMicroservice: 3001
  port: 8881
  tokenSetTimeOut: 7200
  globalPrefix: 'simple-user-center/v1.0'
mysqlConfig:
  host: '148.70.150.131'
  userName: 'root'
  password: '123Ad123Ad'
  dataBaseName: 'prd_simple_user_center'
  port: 3306
mongodbConfig:
  host: '148.70.150.131'
  userName: 'root'
  port: 27017
  dataBaseName: ''
  password: '123ADD123ADD'
  authSource: 'admin'
redisConfig:
  name: 'user_token'
  url: '148.70.150.131:6379'
  host: '148.70.150.131'
  port: 6379
kafkaConfig:
  url: '148.70.150.131:19092'
  clientId: 'test-app-client'
  groupId: 'test-app-group'
rabbitMQConfig:
  url: 'amqp://root:123ADD123ADD@148.70.150.131:5179'
  name: 'MESSAGE_SERVICE'
  queue: 'message_queue'
emailConfig:
  authPass: 'tsdrnaaktxsebfbd'
  fromUser: '"Marvin" <1970305447@qq.com>'
  user: '1970305447@qq.com'
