serverConfig:
  connectMicroservice: 3001
  port: 8881
  tokenSetTimeOut: 7200
  globalPrefix: 'hello-world-center/v1.0'
mysqlConfig:
  host: '127.0.0.1'
  userName: 'root'
  password: '123456'
  dataBaseName: 'b_node_nest_center'
  port: 3306
mongodbConfig:
  host: '127.0.0.1'
  userName: 'root'
  port: 7000
  dataBaseName: ''
  password: '123456'
  authSource: 'admin'
redisConfig:
  name: 'user_token'
  url: '127.0.0.1:6379'
  host: '127.0.0.1'
  port: 6379
kafkaConfig:
  url: ''
  clientId: ''
  groupId: ''
rabbitMQConfig:
    url: ''
    name: ''
    queue: ''
emailConfig:
   authPass: ''
   fromUser: ''
   user: ''
